In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Data Preprocessing

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

### Encoding categorical data

Label Encoding the "Gender" column

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [5]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [9]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Implement ANN using ReLU function

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5173 - accuracy: 0.7944
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4648 - accuracy: 0.8006
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4448 - accuracy: 0.8049
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4349 - accuracy: 0.8074
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4289 - accuracy: 0.8121
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4246 - accuracy: 0.8134: 0s - loss: 0.4254 - accuracy: 
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4220 - accuracy: 0.8148
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4193 - accuracy: 0.8173
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4168 - accuracy: 0.8165
Epoch 10/100
250/250 [==============================] - 1s 

250/250 [==============================] - 1s 4ms/step - loss: 0.3336 - accuracy: 0.8616
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3337 - accuracy: 0.8626: 0s - loss: 0.3228 - ac
Epoch 78/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3330 - accuracy: 0.8625
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3331 - accuracy: 0.8627
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 0.8627
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3326 - accuracy: 0.8633
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3324 - accuracy: 0.8633: 0s - loss: 0.3316 - accuracy: 
Epoch 83/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3328 - accuracy: 0.8644
Epoch 84/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3327 - accuracy: 0.8645
Epoch 85/100
250/250 [=================

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1500   95]
 [ 186  219]]


# Implement ANN using Sigmoid function

In [20]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 10, epochs = 150)

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

Epoch 1/150
800/800 [==============================] - 3s 3ms/step - loss: 0.7184 - accuracy: 0.5679: 
Epoch 2/150
800/800 [==============================] - 2s 3ms/step - loss: 0.4777 - accuracy: 0.7960: 0s - loss: 0.475
Epoch 3/150
800/800 [==============================] - 3s 3ms/step - loss: 0.4548 - accuracy: 0.7959
Epoch 4/150
800/800 [==============================] - 3s 3ms/step - loss: 0.4397 - accuracy: 0.8036
Epoch 5/150
800/800 [==============================] - 2s 3ms/step - loss: 0.4304 - accuracy: 0.8141: 0s - l
Epoch 6/150
800/800 [==============================] - 2s 3ms/step - loss: 0.4237 - accuracy: 0.8152
Epoch 7/150
800/800 [==============================] - 3s 3ms/step - loss: 0.4177 - accuracy: 0.8209: 0s -
Epoch 8/150
800/800 [==============================] - 3s 3ms/step - loss: 0.4128 - accuracy: 0.8253
Epoch 9/150
800/800 [==============================] - 2s 3ms/step - loss: 0.4082 - accuracy: 0.8284
Epoch 10/150
800/800 [==============================] - 3

800/800 [==============================] - 2s 2ms/step - loss: 0.3381 - accuracy: 0.8610
Epoch 76/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3380 - accuracy: 0.8627
Epoch 77/150
800/800 [==============================] - 2s 3ms/step - loss: 0.3378 - accuracy: 0.8625
Epoch 78/150
800/800 [==============================] - 2s 3ms/step - loss: 0.3374 - accuracy: 0.8641
Epoch 79/150
800/800 [==============================] - 2s 3ms/step - loss: 0.3372 - accuracy: 0.8621
Epoch 80/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3375 - accuracy: 0.8602
Epoch 81/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3374 - accuracy: 0.8627
Epoch 82/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3372 - accuracy: 0.8609
Epoch 83/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3368 - accuracy: 0.8614
Epoch 84/150
800/800 [==============================] - 2s 3ms/step - loss: 0.3369 - accuracy: 

# Implement ANN using tanh function

In [21]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='tanh'))
ann.add(tf.keras.layers.Dense(units=6, activation='tanh'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 10, epochs = 150)


Epoch 1/150
800/800 [==============================] - 2s 3ms/step - loss: 0.5008 - accuracy: 0.7582
Epoch 2/150
800/800 [==============================] - 3s 4ms/step - loss: 0.4177 - accuracy: 0.8164
Epoch 3/150
800/800 [==============================] - 2s 3ms/step - loss: 0.4024 - accuracy: 0.8264
Epoch 4/150
800/800 [==============================] - 2s 3ms/step - loss: 0.3897 - accuracy: 0.8325: 0s - loss: 0.3912 
Epoch 5/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3785 - accuracy: 0.8376
Epoch 6/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3686 - accuracy: 0.8445
Epoch 7/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3630 - accuracy: 0.8505
Epoch 8/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3580 - accuracy: 0.8534
Epoch 9/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3550 - accuracy: 0.8539
Epoch 10/150
800/800 [==============================] - 2s 2ms/step - l

Epoch 79/150
800/800 [==============================] - 2s 3ms/step - loss: 0.3362 - accuracy: 0.8639
Epoch 80/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3362 - accuracy: 0.8640
Epoch 81/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3358 - accuracy: 0.8639
Epoch 82/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3360 - accuracy: 0.8633
Epoch 83/150
800/800 [==============================] - 3s 3ms/step - loss: 0.3361 - accuracy: 0.8634
Epoch 84/150
800/800 [==============================] - 3s 3ms/step - loss: 0.3360 - accuracy: 0.8634
Epoch 85/150
800/800 [==============================] - 3s 4ms/step - loss: 0.3360 - accuracy: 0.8648
Epoch 86/150
800/800 [==============================] - 2s 2ms/step - loss: 0.3361 - accuracy: 0.8625: 1s - ETA: 0s - loss: 0
Epoch 87/150
800/800 [==============================] - 2s 3ms/step - loss: 0.3362 - accuracy: 0.8618
Epoch 88/150
800/800 [==============================] - 3s

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1518   77]
 [ 202  203]]
