# Import Numpy

In [1]:
import numpy as np

In [5]:
# Creating an array using the array() function:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Use a tuple to create a NumPy array:
arr = np.array((10,20,30,40,50))
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


# Dimensions in array:

In [8]:
# Create a 0-D array with value 42
arr = np.array(42)
print(arr)

42


In [10]:
# Create a 1-D array containing the values 1,2,3,4,5:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [12]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
# Create a 3-D array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
# Higher Dimensional Arrays
arr = np.array([1,2,3],ndmin=5)
print(arr)
print("Dimensions are: {}".format(arr.ndim))

[[[[[1 2 3]]]]]
Dimensions are: 5


# NumPy Array Indexing

In [21]:
# Get the first element from the following array:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [22]:
# Access the 2nd element on 1st dim:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [26]:
# Access the third element of the second array of the first array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [27]:
# Negative Indexing
# Use negative indexing to access an array from the end.
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# Slicing arrays

In [29]:
# Slice elements from index 1 to index 5 from the following array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [35]:
# Negative Slicing
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [37]:
# STEP
# Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [38]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


# COPY:

In [41]:
# Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print("arr: {}".format(arr))
print("x: {}".format(x))

arr: [42  2  3  4  5]
x: [1 2 3 4 5]


In [44]:
# VIEW:
# Make a view, change the original array, and display both arrays:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print("arr:",arr)
print("x:",x)

arr: [42  2  3  4  5]
x: [42  2  3  4  5]


# Shape of an Array

In [45]:
# Print the shape of a 2-D array:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [47]:
# C?reate an array with 5 dimensions using ndmin using a vector with values
# ?1,2,3,4 and verify that last dimension has value 4:

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Reshaping arrays

In [48]:
# Convert the following 1-D array with 12 elements into a 2-D array.The
# outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Flattening the arrays

In [49]:
# Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# Iterating Arrays

In [51]:
# Iterate on the elements of the following 1-D array:
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [52]:
# Iterate on each scalar element of the 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [53]:
# Iterating Arrays Using nditer()
# Iterate through the following 3-D array:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# Joining NumPy Arrays

In [54]:
# Join two arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [55]:
# Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Splitting NumPy Arrays

In [56]:
# Split the array in 3 parts:

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [57]:
# Splitting 2-D Arrays
# Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [58]:
# Split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14,
15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Arrays

In [59]:
# Find the indexes where the value is 4:

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [60]:
# Search Sorted
# Find the indexes where the value 7 should be inserted:

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [61]:
# Search From the Right Side
# Find the indexes where the value 7 should be inserted, starting from the right:

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


# NumPy Sorting Arrays

In [63]:
# Sort the array:
# Note: This method returns a copy of the array, leaving the original array
# unchanged.

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [64]:
# Sort the array alphabetically:

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


# Filtering Arrays

In [65]:
# Create an array from the elements on index 0 and 2:

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
print(arr[x])

[41 43]


In [66]:
# Creating the Filter Array
# Create a filter array that will return only values higher than 42:

arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
# if the element is higher than 42, set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [68]:
# Creating Filter Directly From Array
# Create a filter array that will return only values higher than 42:

arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [69]:
# Create a filter array that will return only even elements from the original
# array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
